### ISSUE TITLE
no data received since 2017-05-12

### ISSUE THREAD

**Issue by LoveMyData** [otherchirps/noosa_council#4]
Looks like URL changed

New site
https://noo-web.t1cloud.com/T1PRDefault/WebApps/eProperty/P1/eTrack/eTrackApplicationSearchResults.aspx?Field=S&Period=TM&r=P1.WEBGUEST&f=$P1.ETR.SEARCH.STM

**Comment by otherchirps** [comment]
Looks like upstream has thrown out the python code.  Closing.
